name: Manual E2E Test Run

on:
  workflow_dispatch:
    inputs:
      suite:
        type: choice
        description: Select test suite
        default: all
        options:
          - all
          - find
          - applicant
          - admin
          - superadmin
      specs:
        type: string
        description: (optional) enter spec files, will override suites above
        required: false
      browser:
        type: choice
        description: Select browser to run tests against
        default: all
        options:
          - all
          - chrome
          - firefox
          - webkit
      report:
        type: choice
        description: Upload report?
        default: "false"
        options:
          - false
          - true
      notify:
        type: choice
        description: Notify on Slack?
        default: "false"
        options:
          - false
          - true
      environment:
        type: choice
        description: Environment
        default: SANDBOX
        options:
          - SANDBOX
          - QA

jobs:
  call-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      specs: ${{ inputs.specs != '' && inputs.specs || inputs.suite == 'all' && 'cypress/e2e/**/*' || format('cypress/e2e/{0}/**/*', inputs.suite) }}
      browser: ${{ inputs.browser }}
      report: ${{ inputs.report }}
      notify: ${{ inputs.notify }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    if: ${{ !cancelled() && inputs.browser != 'all' }}

  call-reusable-multi-browser-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_multi_browser_e2e_test_run.yml
    with:
      specs: ${{ inputs.suite == 'all' && 'cypress/e2e/**/*' || format('cypress/e2e/{0}/**/*', inputs.suite) }}
      report: ${{ inputs.report }}
      notify: ${{ inputs.notify }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    if: ${{ !cancelled() && inputs.browser == 'all' }}
