name: Manual E2E Test Run

on:
  workflow_dispatch:
    inputs:
      suite:
        type: choice
        description: Select test suite
        default: all
        options:
          - all
          - find
          - apply
          - admin
          - superadmin
      browser:
        type: choice
        description: Select browser to run tests against
        default: all
        options:
          - all
          - chrome
          - firefox
          - webkit
      report:
        type: choice
        description: Upload report?
        default: false
        options:
          - false
          - true
      environment:
        type: choice
        description: Environment
        default: SANDBOX
        options:
          - SANDBOX
          - QA

jobs:
  call-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: ${{ inputs.suite }}
      browser: ${{ inputs.browser }}
      report: ${{ inputs.report }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    if: ${{ !cancelled() && inputs.browser != 'all' }}

  call-reusable-multi-browser-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_multi_browser_e2e_test_run.yml
    with:
      suite: ${{ inputs.suite }}
      report: ${{ inputs.report }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    if: ${{ !cancelled() && inputs.browser == 'all' }}
