name: Push E2E Test Run

on:
  push:
    branches:
      - feature/**
      - fix/**
      - bug/**
      - develop
      - main
      - TD**
      - GAP**
    paths-ignore:
      - "*.md"

jobs:
  call-chrome-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: chrome
      report: yes
    secrets: inherit

        
  call-firefox-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: firefox
      report: yes
    secrets: inherit
    needs: call-chrome-reusable-e2e-test-run-workflow
