name: Push E2E Test Run

on:
  push:
    branches:
      - feature/**
      - fix/**
      - FIX-**
      - bug/**
      - develop
      - main
      - TD**
      - GAP**
      - TMI**
      - release/**
    paths-ignore:
      - "*.md"

jobs:
  call-chrome-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: chrome
      report: false
      environment: sandbox
    secrets: inherit
