name: Push E2E Test Run

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "**.md"
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "**.md"

jobs:
  detect-suites:
    runs-on: ubuntu-latest
    outputs:
      suite: ${{ steps.determine_suite.outputs.suite }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: changed_files

      - name: Set changed suites array
        id: changed_suites_array
        run: |
          CHANGED_SUITES_ARRAY=()
          if [[ ${{ contains(steps.changed_files.outputs.all, 'cypress/e2e/admin/') }} ]]; then
            CHANGED_SUITES_ARRAY+=("admin")
          fi
          if [[ ${{ contains(steps.changed_files.outputs.all, 'cypress/e2e/applicant/' ) }} ]]; then
            CHANGED_SUITES_ARRAY+=("applicant")
          fi
          if [[ ${{ contains(steps.changed_files.outputs.all, 'cypress/e2e/superadmin/') }} ]]; then
            CHANGED_SUITES_ARRAY+=("superadmin")
          fi
          if [[ ${{ contains(steps.changed_files.outputs.all, 'cypress/e2e/find/') }} ]]; then
            CHANGED_SUITES_ARRAY+=("find")
          fi
          echo "changed_suites_array=$CHANGED_SUITES_ARRAY" >> "$GITHUB_OUTPUT"

      - name: Set force_run_all_suites
        id: force_run_all_suites
        run: |
          VALUE=${{ contains(steps.changed_files.outputs.all, 'cypress/common') || contains(steps.changed_files.outputs.all, 'cypress/seed') || contains(steps.changed_files.outputs.all, 'cypress.config.ts') || contains(steps.changed_files.outputs.all, 'cypress/support') || contains(steps.changed_files.outputs.all, 'cypress/fixtures') }}
          echo "force_run_all_suites=$VALUE" >> "$GITHUB_OUTPUT"

      - name: Determine suite
        id: determine_suite
        run: |
          if [[ ${{ steps.force_run_all_suites.outputs.force_run_all_suites }} == true ]]; then
            echo "suite=all" >> "$GITHUB_OUTPUT"
          else
            echo "suite=${{ join(steps.changed_suites_array.outputs.changed_suites_array, ',') }}" >> "$GITHUB_OUTPUT"
          fi

  call-sandbox-chrome-reusable-e2e-test-run-workflow:
    needs: detect-suites
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: ${{ needs.detect-suites.outputs.suite }}
      browser: chrome
      report: false
      notify: false
      environment: SANDBOX
    secrets: inherit
