name: Push E2E Test Run

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - "**.md"
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "**.md"

jobs:
  detect-specs:
    runs-on: ubuntu-latest
    outputs:
      specs: ${{ steps.determine_specs.outputs.specs }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: changed_files

      - name: Determine changed specs
        id: changed_specs
        run: echo "Hi"

      - name: Set force_run_all_suites
        id: force_run_all_suites
        run: |
          VALUE=${{ steps.changed_specs.outputs.changed_specs == null || contains(steps.changed_files.outputs.all, 'cypress/common') || contains(steps.changed_files.outputs.all, 'cypress/seed') || contains(steps.changed_files.outputs.all, 'cypress.config.ts') || contains(steps.changed_files.outputs.all, 'cypress/support') || contains(steps.changed_files.outputs.all, 'cypress/fixtures') || contains(steps.changed_files.outputs.all, 'package.json') || contains(steps.changed_files.outputs.all, '.github/workflows/push_e2e_test_run.yml') || contains(steps.changed_files.outputs.all, '.github/workflows/reusable_e2e_test_run.yml') }}
          echo "force_run_all_suites=$VALUE" >> "$GITHUB_OUTPUT"

      - name: Determine specs to run
        id: determine_specs
        run: |
          if [[ ${{ steps.force_run_all_suites.outputs.force_run_all_suites }} == true ]]; then
            echo "specs=all" >> "$GITHUB_OUTPUT"
          else
            echo "specs=${{ steps.changed_specs.outputs.changed_specs }}" >> "$GITHUB_OUTPUT"
          fi

  call-sandbox-chrome-reusable-e2e-test-run-workflow:
    needs: detect-specs
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      specs: ${{ needs.detect-specs.outputs.specs }}
      browser: chrome
      report: false
      notify: false
      environment: SANDBOX
    secrets: inherit
