name: Push E2E Test Run

on:
  pull_request:
    branches: develop

jobs:
  call-sandbox-chrome-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: chrome
      report: true
      environment: SANDBOX
    secrets: inherit
