name: Push E2E Test Run

on:
  pull_request:
    branches: develop
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "*.md"

jobs:
  call-sandbox-chrome-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: firefox
      report: false
      notify: false
      environment: SANDBOX
    secrets: inherit
