name: Reusable Multi-Browser E2E Test Run Workflow

on:
  workflow_call:
    inputs:
      specs:
        default: cypress/e2e/**/*
        type: string
      report:
        default: "false"
        type: string
      notify:
        default: "false"
        type: string
      environment:
        default: SANDBOX
        type: string
      branch:
        default: ./
        type: string
      repeat:
        default: 1
        type: number
jobs:
  call-chrome-reusable-e2e-test-run-workflow:
    name: Chrome E2E Test Run
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      specs: ${{ inputs.specs }}
      browser: chrome
      report: ${{ inputs.report }}
      notify: ${{ inputs.notify }}
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      repeat: ${{ inputs.repeat }}
    secrets: inherit

  call-firefox-reusable-e2e-test-run-workflow:
    name: Firefox E2E Test Run
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      specs: ${{ inputs.specs }}
      browser: firefox
      report: ${{ inputs.report }}
      notify: ${{ inputs.notify }}
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      repeat: ${{ inputs.repeat }}
    secrets: inherit
    needs: call-chrome-reusable-e2e-test-run-workflow
    if: always()

  # =============================
