name: Reusable Multi-Browser E2E Test Run Workflow

on:
  workflow_call:
    inputs:
      suite:
        default: all
        type: string
      report:
        default: false
        type: string
      environment:
        default: sandbox
        type: string

jobs:
  call-chrome-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: ${{ inputs.suite }}
      browser: chrome
      report: ${{ inputs.report }}
      environment: ${{ inputs.environment }}
    secrets: inherit

  call-firefox-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: ${{ inputs.suite }}
      browser: firefox
      report: ${{ inputs.report }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    needs: call-chrome-reusable-e2e-test-run-workflow
    if: { { !cancelled()  } }

  # =============================
