name: Reusable E2E Test Run

on:
  workflow_call:
    inputs:
      suite:
        default: all
        type: string
      browser:
        default: chrome
        type: string
      report:
        default: false
        type: string
      environment:
        default: sandbox
        type: string

jobs:
  reusable_e2e_test_run:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    concurrency: e2e_test_run

    steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Add Github Actions IP to Security group
        run: |
          echo "${{ steps.ip.outputs.ipv4 }}"
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.${{ inputs.environment.uppercase }}_AWS_VPC_SG_ID }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}

      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Generate .env
        run: |
          cat << EOF > .env
          ONE_LOGIN_BASE_URL=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_SANDBOX_BASE_URL }}
          ONE_LOGIN_USERNAME=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_SANDBOX_USERNAME }}
          ONE_LOGIN_PASSWORD=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_SANDBOX_PASSWORD }}
          APPLICATION_BASE_URL=${{ secrets.${{ inputs.environment.uppercase }}_APPLICATION_BASE_URL }}
          POST_LOGIN_BASE_URL=${{ secrets.${{ inputs.environment.uppercase }}_POST_LOGIN_BASE_URL }}
          ONE_LOGIN_APPLICANT_EMAIL=${{ secrets.ONE_LOGIN_APPLICANT_EMAIL }}
          ONE_LOGIN_APPLICANT_PASSWORD=${{ secrets.ONE_LOGIN_APPLICANT_PASSWORD }}
          ONE_LOGIN_APPLICANT_SUB=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_APPLICANT_SUB }}
          ONE_LOGIN_ADMIN_EMAIL=${{ secrets.ONE_LOGIN_ADMIN_EMAIL }}
          ONE_LOGIN_ADMIN_PASSWORD=${{ secrets.ONE_LOGIN_ADMIN_PASSWORD }}
          ONE_LOGIN_ADMIN_SUB=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_ADMIN_SUB }}
          ONE_LOGIN_SUPER_ADMIN_EMAIL=${{ secrets.ONE_LOGIN_SUPER_ADMIN_EMAIL }}
          ONE_LOGIN_SUPER_ADMIN_PASSWORD=${{ secrets.ONE_LOGIN_SUPER_ADMIN_PASSWORD }}
          ONE_LOGIN_SUPER_ADMIN_SUB=${{ secrets.${{ inputs.environment.uppercase }}_ONE_LOGIN_SUPER_ADMIN_SUB }}
          AWS_VPC_SG_ID=${{ secrets.${{ inputs.environment.uppercase }}_AWS_VPC_SG_ID }}
          USERS_DATABASE_URL =${{ secrets.${{ inputs.environment.uppercase }}_CYPRESS_USERS_DATABASE_URL }}
          USERS_DATABASE_NAME=${{ secrets.${{ inputs.environment.uppercase }}_CYPRESS_USERS_DATABASE_NAME }}
          APPLY_DATABASE_URL =${{ secrets.${{ inputs.environment.uppercase }}_CYPRESS_APPLY_DATABASE_URL }}
          APPLY_DATABASE_NAME=${{ secrets.${{ inputs.environment.uppercase }}_CYPRESS_APPLY_DATABASE_NAME }}
          CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN=${{ secrets.${{ inputs.environment.uppercase }}_CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ENVIRONMENT_ID=${{ inputs.environment.uppercase }}_${{ vars.CONTENTFUL_ENVIRONMENT_ID }}
          EOF

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir-path.outputs.dir }}
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run cy:run:${{ inputs.suite }} -- --browser ${{ inputs.browser }}

      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.${{ inputs.environment.uppercase }}_AWS_VPC_SG_ID }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        if: always()

      - name: Upload Report to S3
        # there should be only one report generated from the run, so grab it for manipulation
        # the filename will either start with pass_ or fail_ and we want to put the browser info between this status and the timestamp
        # so replace any instance of pass_ with pass_{browser}_
        # then replace any instance of fail_ with fail_{browser}_
        # then rename the file to this new name so that the browser info is attached to the report
        # then upload to s3 as normal
        run: |
          FILE_PATH="/home/runner/work/gap-automated-tests/gap-automated-tests/mochawesome-report"
          OLD_FILENAME=$(ls -a -d $FILE_PATH/*)
          NEW_PASS_FILENAME=${OLD_FILENAME/pass_/pass_${{ inputs.browser }}_}
          NEW_FAIL_FILENAME=${NEW_PASS_FILENAME/fail_/fail_${{ inputs.browser }}_}
          mv $OLD_FILENAME $NEW_FAIL_FILENAME
          aws s3 cp $FILE_PATH/ s3://gap-automated-tests/${{ inputs.environment }} --recursive --exclude "*" --include "*.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        if: ${{ !cancelled() && inputs.report == 'true' }}

      - name: Presign S3 report for sharing
        run: |
          FILE_PATH="/home/runner/work/gap-automated-tests/gap-automated-tests/mochawesome-report"
          FULL_FILE_PATH=$(ls -a -d $FILE_PATH/*)
          FILENAME=${FULL_FILE_PATH/$FILE_PATH/}
          aws s3 presign s3://gap-automated-tests/${{ inputs.environment }}$FILENAME --expires-in 604800
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        if: ${{ !cancelled() && inputs.report == 'true' }}
