name: Scheduled E2E Test Run Workflow

on:
  schedule:
    - cron: "0 4 * * 1-5" # every weekday at 4am

jobs:
  call-reusable-e2e-test-run-workflow:
    uses: ./.github/workflows/reusable_e2e_test_run.yml
    with:
      suite: all
      browser: chrome
      environment: dev
    secrets: inherit

  # =============================
